-- Position-based leave and late policies
-- Run in Supabase SQL Editor before starting the app.

create table if not exists public.position_policies (
  id bigint generated by default as identity primary key,
  role_key text not null,
  fiscal_year integer not null,
  sick_leave_days integer not null default 30,
  personal_leave_days integer not null default 15,
  late_limit_count integer not null default 5,
  grace_minutes integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null,

  constraint position_policies_role_key_check
    check (role_key in ('director', 'teacher', 'staff', 'janitor')),

  constraint position_policies_fiscal_year_check
    check (fiscal_year between 2500 and 2700),

  constraint position_policies_sick_leave_days_check
    check (sick_leave_days >= 0),

  constraint position_policies_personal_leave_days_check
    check (personal_leave_days >= 0),

  constraint position_policies_late_limit_count_check
    check (late_limit_count >= 0),

  constraint position_policies_grace_minutes_check
    check (grace_minutes between 0 and 180),

  constraint position_policies_role_year_unique
    unique (role_key, fiscal_year)
);

create index if not exists position_policies_year_role_idx
  on public.position_policies (fiscal_year, role_key);

alter table public.position_policies enable row level security;

drop policy if exists "Authenticated users can read position policies"
  on public.position_policies;

create policy "Authenticated users can read position policies"
  on public.position_policies
  for select
  to authenticated
  using (is_active = true);

-- Insert defaults for the active fiscal year.
insert into public.position_policies (
  role_key,
  fiscal_year,
  sick_leave_days,
  personal_leave_days,
  late_limit_count,
  grace_minutes,
  is_active
)
select
  role_key,
  coalesce(active_fiscal_year, 2569),
  30,
  15,
  5,
  0,
  true
from public.attendance_settings
cross join (
  values
    ('director'),
    ('teacher'),
    ('staff'),
    ('janitor')
) as roles(role_key)
where id = 1
on conflict (role_key, fiscal_year) do nothing;

notify pgrst, 'reload schema';
